{% set version = '2.18.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstan
  version: {{ version|replace("-", "_") }}

source:
  fn: rstan_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rstan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstan/rstan_{{ version }}.tar.gz
  sha256: 8e5d4a6649099c8e284c7694dbd15a396c75d710f935a05ac52c679a37a99c05

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh >=1.66
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-stanheaders >=2.18.0
    - r-ggplot2 >=2.0.0
    - r-gridextra >=2.0.0
    - r-inline
    - r-loo >=2.0.0
    - r-pkgbuild
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh >=1.66
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-stanheaders >=2.18.0
    - r-ggplot2 >=2.0.0
    - r-gridextra >=2.0.0
    - r-inline
    - r-loo >=2.0.0
    - r-pkgbuild

test:
  commands:
    - $R -e "library('rstan')"           # [not win]
    - "\"%R%\" -e \"library('rstan')\""  # [win]

about:
  home: http://discourse.mc-stan.org, http://mc-stan.org
  license: GPL (>= 3)
  summary: User-facing R functions are provided to parse, compile, test, estimate, and analyze
    Stan models by accessing the header-only Stan library provided by the 'StanHeaders'
    package. The Stan project develops a probabilistic programming language that implements
    full Bayesian statistical inference via Markov Chain Monte Carlo, rough Bayesian
    inference via 'variational' approximation, and (optionally penalized) maximum likelihood
    estimation via optimization. In all three cases, automatic differentiation is used
    to quickly and accurately evaluate gradients without burdening the user with the
    need to derive the partial derivatives.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
