{% set version = "2.26.23" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstan
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rstan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstan/rstan_{{ version }}.tar.gz
  sha256: 91fddeb9460755e02b7fbc7caa964df8d0d77417528ae96ce3e2f6d56fe60d22

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-loo                      # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-rcppeigen                # [build_platform != target_platform]
    - r-v8                       # [build_platform != target_platform]
    - r-bh                       # [build_platform != target_platform]
    - r-rcppparallel             # [build_platform != target_platform]
    - r-stanheaders              # [build_platform != target_platform]
    - r-inline                   # [build_platform != target_platform]
    - r-pkgbuild                 # [build_platform != target_platform]
    - r-gridextra                # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.72.0_2
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-stanheaders >=2.21.0
    - r-v8
    - r-ggplot2 >=3.0.0
    - r-gridextra >=2.0.0
    - r-inline
    - r-loo >=2.3.0
    - r-pkgbuild
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-stanheaders >=2.21.0
    - r-v8
    - r-ggplot2 >=3.0.0
    - r-gridextra >=2.0.0
    - r-inline
    - r-loo >=2.3.0
    - r-pkgbuild
    - r-withr

test:
  commands:
    - $R -e "library('rstan')"           # [not win]
    - "\"%R%\" -e \"library('rstan')\""  # [win]

about:
  home: http://discourse.mc-stan.org, http://mc-stan.org
  license: GPL-3.0-or-later
  summary: User-facing R functions are provided to parse, compile, test, estimate, and analyze Stan models by accessing the header-only Stan library provided by the 'StanHeaders' package. The Stan project develops a probabilistic programming language that implements full Bayesian statistical inference via Markov Chain Monte
    Carlo, rough Bayesian inference via 'variational' approximation, and (optionally penalized) maximum likelihood estimation via optimization. In all three cases, automatic differentiation is used to quickly and accurately evaluate gradients without burdening the user with the need to derive the partial derivatives.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rluria14
    - oblute
    - ndmaxar
